// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lasitqorbmucgywsfacp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhc2l0cW9yYm11Y2d5d3NmYWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjg2MTUsImV4cCI6MjA2NDk0NDYxNX0.simX44FBZBUFGZk3S1FWZqvoqJ7MaTj8eFod6E9MQyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});